### ISSUE TITLE
Resume booklet is out of date

### ISSUE THREAD

**Issue by kevingreenman** [tbpmig/mig-website#234]
Resumes should be removed from the resume booklet after graduation. There are currently some resumes in the undergraduate folder of people who graduated in 2014, 2015, and 2016. It would also be nice to have a reminder email automatically sent out to people when they haven’t updated their resume in over a year.

**Comment by mikehand** [comment]
is the existing reminder to note yourself as graduated insufficient for
this?

**Comment by kevingreenman** [comment]
Yes. There are currently almost 120 resumes in the "undergraduate-student" and "graduate-student" folders for the graduation years 2014-2017.

**Comment by mikehand** [comment]
Ok I think the better solution here is to allow the membership officer the
ability to mark people as graduated if they’ve not updated their stuff.
Assuming the resume stuff ignores alumni this should fix it yes?

**Comment by kevingreenman** [comment]
That would help, but that really only fixes the problem for one of the resume booklets. There's the option to download it sorted by either graduation year or by major. Marking them as graduated would sort their resumes into the "alumni" folder of the booklet sorted by graduation year, but their resumes would still appear along with anyone else's in the booklet sorted by major. We spoke about this at a recent officer meeting and there was a general consensus that the resume booklet should only be for current students.

**Comment by mikehand** [comment]
Ok I thought that was included in the filtering I’ll take a look

**Comment by kevingreenman** [comment]
Do you have an estimate of when this will be taken care of?

**Comment by mikehand** [comment]
I've got it so that it will exclude alumni from the book. Looking into the
ability of the membership officer to mark people graduated. I'll push the
first part this evening

**Comment by kevingreenman** [comment]
Do you have an update on when you think the membership officer will have the ability to mark people as graduated?

**Comment by mikehand** [comment]
I do not. As I’ve said before, I’ll handle bugs when I can but requests for
new features are a very low priority. The chapter needs to start figuring
out how to get a new website chair up to speed

**Comment by kevingreenman** [comment]
I agree regarding the website chair. That being said, I would appreciate it if you could move this higher on the priority list of new feature requests, given that it impacts how we interact with companies and isn't simply something for convenience

**Comment by kevingreenman** [comment]
Thanks for making the change. Do you know when we can expect the next deploy so we can start using this feature?

**Comment by kylelady** [comment]
If the code is done, I'm able to deploy the site, fwiw. Not that it's all
that hard either...

**Comment by mikehand** [comment]
Should be good to run the deploy script. Let me know if you hit issues
